services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_DATA_LOCATION}:/root/.ollama
    restart: unless-stopped
    entrypoint: /bin/sh -c "
      ollama pull mistral &&  
      ollama run mistral &    
      /bin/ollama serve       
      "

  postgres:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: video-vector
    volumes:
      - ${VECTOR_DATA_LOCATION}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "8383:80"
    depends_on:
      - postgres