server:
  servlet:
    context-path: /api
  port: 8181
spring:
  application:
    name: rag-video-recomender

  ai:
    ollama:
      chat:
        model: mistral
        base-url: http://localhost:11434
      embedding:
        model: mistral
    vectorstore:
      pgvector:
        url: jdbc:postgresql://localhost:5432/videos
        username: user
        password: pass
